# Regression Models - Error Evaluation

This notebook demonstrates the fundamentals of simple linear regression and evaluates model performance using MSE, RMSE, and MAE.

The objective is to predict employee salaries based on years of experience using a predefined linear regression equation.

## 1. Problem Definition

Given employee experience and salary data, construct a simple linear regression model using the provided bias and weight values, generate salary predictions, and evaluate prediction errors.

In [1]:
import pandas as pd
import numpy as np

experience = [5, 7, 3, 3, 2, 7, 3, 10, 6, 4, 8, 1, 1, 9, 1]
salary = [600, 900, 550, 500, 400, 950, 540, 1200, 900, 550, 1100, 460, 400, 1000, 380]

df = pd.DataFrame({
    "Experience": experience,
    "Salary": salary
})

df

    Experience  Salary
0            5     600
1            7     900
2            3     550
3            3     500
4            2     400
5            7     950
6            3     540
7           10    1200
8            6     900
9            4     550
10           8    1100
11           1     460
12           1     400
13           9    1000
14           1     380

## 2. Simple Linear Regression

A simple linear regression model predicts the target variable using a straight-line equation.

The regression equation is:

\[
\hat{y}=b+wx
\]

where:

- **ŷ** = Predicted salary
- **b** = Bias (Intercept)
- **w** = Weight (Slope)
- **x** = Years of experience

For this exercise:

- Bias = **275**
- Weight = **90**

## 3. Define the Regression Model

A simple linear regression model predicts the target variable using a straight-line equation.

For this exercise, the model parameters are predefined:

- Bias (Intercept) = 275
- Weight (Slope) = 90

The prediction equation is:

\[
\hat{y} = 275 + 90 \times x
\]

In [3]:
# Define model parameters
bias = 275
weight = 90

# Calculate predicted salaries
df["Prediction"] = bias + weight * df["Experience"]

df.head()

   Experience  Salary  Prediction
0           5     600         725
1           7     900         905
2           3     550         545
3           3     500         545
4           2     400         455

## 3. Calculate Prediction Errors

The prediction error (also called the residual) is the difference between the actual salary and the predicted salary.

Three different error values will be calculated:

- Prediction Error
- Absolute Error
- Squared Error

In [6]:
# Prediction Error (Residual)
df["Error"] = df["Salary"] - df["Prediction"]

# Absolute Error
df["Absolute_Error"] = df["Error"].abs()

# Squared Error
df["Squared_Error"] = df["Error"] ** 2

df

    Experience  Salary  Prediction  Error  Absolute_Error  Squared_Error
0            5     600         725   -125             125          15625
1            7     900         905     -5               5             25
2            3     550         545      5               5             25
3            3     500         545    -45              45           2025
4            2     400         455    -55              55           3025
5            7     950         905     45              45           2025
6            3     540         545     -5               5             25
7           10    1200        1175     25              25            625
8            6     900         815     85              85           7225
9            4     550         635    -85              85           7225
10           8    1100         995    105             105          11025
11           1     460         365     95              95           9025
12           1     400         365     35              35           1225
13           9    1000        1085    -85              85           7225
14           1     380         365     15              15            225

## 4. Regression Error Metrics

Evaluate the regression model using three common regression metrics:

- Mean Absolute Error (MAE)
- Mean Squared Error (MSE)
- Root Mean Squared Error (RMSE)

In [7]:
# Mean Absolute Error
mae = df["Absolute_Error"].mean()

# Mean Squared Error
mse = df["Squared_Error"].mean()

# Root Mean Squared Error
rmse = np.sqrt(mse)

print(f"MAE : {mae:.2f}")
print(f"MSE : {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

MAE : 54.33
MSE : 4438.33
RMSE: 66.62

## 5. Interpretation

- **MAE** measures the average magnitude of prediction errors.
- **MSE** squares each error, giving greater importance to larger mistakes.
- **RMSE** is the square root of MSE and is expressed in the same unit as the target variable, making it easier to interpret.